import Button from '@/components/atoms/Button';
import React from 'react';
import './page.scss';
export const metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
};
const About = () => {
  return (
    <div>
      About Page
      <Button  kind=''>Lê Trunks</Button>
      <h1 className='title'>Test variable scss</h1>
    </div>
  );
};

export default About;
